In [1]:
# Import packages
import numpy as np
curDay = 9

# Download input file
from download_inputs import download_inputs


import os
filename = f'inputs\\day{curDay}.txt'
if not os.path.exists(filename):
    download_inputs(curDay)
else:
    print('Inputs already downloaded')

200


In [106]:
# Load input into workspace
filename = f'inputs\\day{curDay}.txt'
# curIn = np.loadtxt(filename)

inputFile = open(filename)
inputs = [s for s in inputFile.read().splitlines()]

print('Done loading input')

Done loading input


In [107]:
# Load test-input into workspace
filenameTest = f'inputs\\day{curDay}_test.txt'

inputFileTest = open(filenameTest)
inputsTest = [s for s in inputFileTest.read().splitlines()]

print('Done loading test-input') 

Done loading test-input


# Input parsing

In [113]:
def parseIn(curIn):
        
    seqs = []

    for li in curIn:
        seqs.append([int(x) for x in li.split()])
    seqs = np.array(seqs)

    parsed = seqs 
    return parsed 

# parseIn(inputs)
# parseIn(inputsTest)

# Functionalized solutions

In [121]:
seqs = parseIn(inputs)
# seqs = parseIn(inputsTest)

In [145]:
def sequenceToDifference(curS):
    #### Determine lists of differences

    # Initialize and append starting sequence
    allDiffs = []
    allDiffs.append(curS)
    curDiff = curS

    # While any values are nonzero
    nonZero = True 
    while nonZero:
        # Get the difference of the current line
        nextDiff = np.diff(curDiff)
        # Append it to array
        allDiffs.append(nextDiff)
        # set the current line to the next
        curDiff = nextDiff
        
        # Check if all values are zero
        if np.all(np.unique(curDiff) == 0):
            nonZero = False

    return allDiffs 

In [146]:
def extrapolateForward(allDiffs):
    #### Extrapolate forward and append to arrays

    # Go through lines backwards
    for i in range(-1,-len(allDiffs)-1,-1):
        if i == -1:
            # At the bottom line, just use zero
            valToAppend = 0
        else:
            # At all other lines, use the last value plus the last value below it
            valToAppend = allDiffs[i][-1] + allDiffs[i+1][-1]

        # Append the extrapolated value to the array
        allDiffs[i] = np.append(allDiffs[i],valToAppend)
    
    return allDiffs 

In [147]:
def extrapolateBackward(allDiffs):    
    #### Extrapolate backwards and insert in front

    # Go through lines backwards
    for i in range(-1,-len(allDiffs)-1,-1):
        if i == -1:
            # At the bottom line, just use zero
            valToAppend = 0
        else:
            # At all other lines, use the first value, plus the first value below it
            valToAppend = allDiffs[i][0] - allDiffs[i+1][0]

        # Insert the extrapolated value at position 0 of the array
        allDiffs[i] = np.insert(allDiffs[i],0,valToAppend)
    
    return allDiffs 

In [148]:
sol1 = 0
sol2 = 0

# Go through the sequences
for curS in seqs:  

    allDiffs = sequenceToDifference(curS)
    allDiffsForward = extrapolateForward(allDiffs.copy())
    allDiffsBackward = extrapolateBackward(allDiffs.copy())

    sol1 += allDiffsForward[0][-1]
    sol2 += allDiffsBackward[0][0]
    
print(f'Solution to part 1: {sol1}')
print(f'Solution to part 2: {sol2}')

Solution to part 1: 1798691765
Solution to part 2: 1104


# Part 1

In [140]:
sol1 = 0

# Go through the sequences
for seqi in range(len(seqs)):

    curS = seqs[seqi]

    #### Determine lists of differences
    allDiffs = []
    allDiffs.append(curS)

    curDiff = allDiffs[-1]
    nonZero = True 
    while nonZero:
        nextDiff = np.diff(curDiff)
        allDiffs.append(nextDiff)
        curDiff = nextDiff
        
        if np.all(np.unique(curDiff) == 0):
            nonZero = False


    #### Append 
    for i in range(-1,-len(allDiffs)-1,-1):
        if i == -1:
            valToAppend = 0
        else:
            valToAppend = allDiffs[i][-1] + allDiffs[i+1][-1]

        allDiffs[i] = np.append(allDiffs[i],valToAppend)

    sol1 += allDiffs[0][-1]

print(sol1)

1798691765


# Part 2

In [141]:
seqs = parseIn(inputs)
# seqs = parseIn(inputsTest)

In [142]:
sol2 = 0

# Go through
for seqi in range(len(seqs)):

    curS = seqs[seqi]

    #### Determine lists of differences
    allDiffs = []
    allDiffs.append(curS)

    curDiff = allDiffs[-1]
    nonZero = True 
    while nonZero:
        nextDiff = np.diff(curDiff)
        allDiffs.append(nextDiff)
        curDiff = nextDiff

        if np.all(np.unique(curDiff) == 0):
            nonZero = False

    #### Insert in front
    for i in range(-1,-len(allDiffs)-1,-1):
        if i == -1:
            valToAppend = 0
        else:
            valToAppend = allDiffs[i][0] - allDiffs[i+1][0]

        # allDiffs[i] = np.append(allDiffs[i],valToAppend)
        allDiffs[i] = np.insert(allDiffs[i],0,valToAppend)
        # print(allDiffs)
    

    #### Add to solution
    sol2 += allDiffs[0][0]


print(sol2)

1104


In [126]:
print(f'Solution to part 1: {sol1}')
print(f'Solution to part 2: {sol2}')

Solution to part 1: 1798691765
Solution to part 2: 1104


# Old below

In [65]:
seqs
i = 0

curS = seqs[i]

allDiffs = []
allDiffs.append(curS)

curDiff = allDiffs[-1]
while curDiff[1] != 0:
    nextDiff = np.diff(curDiff)
    allDiffs.append(nextDiff)
    curDiff = nextDiff

    

# np.diff(curS)
# curDiff
allDiffs 



[array([ 0,  3,  6,  9, 12, 15]), array([3, 3, 3, 3, 3]), array([0, 0, 0, 0])]

In [66]:
# valToAppend = 0

for i in range(-1,-len(allDiffs)-1,-1):
    if i == -1:
        valToAppend = 0
    else:
        valToAppend = allDiffs[i][-1] + allDiffs[i+1][-1]

    allDiffs[i] = np.append(allDiffs[i],valToAppend)
allDiffs

[array([ 0,  3,  6,  9, 12, 15, 18]),
 array([3, 3, 3, 3, 3, 3]),
 array([0, 0, 0, 0, 0])]

In [54]:
i = -1
valToAppend = allDiffs[i][-1]
valToAppend


allDiffs[i] = np.append(allDiffs[i],valToAppend)


allDiffs

[array([ 0,  3,  6,  9, 12, 15]),
 array([3, 3, 3, 3, 3]),
 array([0, 0, 0, 0, 0])]

In [55]:
for i in range(-2,-len(allDiffs)-1,-1):
    valToAppend = allDiffs[i][-1] + allDiffs[i+1][-1]


    allDiffs[i] = np.append(allDiffs[i],valToAppend)
allDiffs

[array([ 0,  3,  6,  9, 12, 15, 18]),
 array([3, 3, 3, 3, 3, 3]),
 array([0, 0, 0, 0, 0])]

In [56]:
allDiffs[0][-1]

18

In [42]:
# i = -3
# valToAppend = allDiffs[i][-1] + allDiffs[i+1][-1]


# allDiffs[i] = np.append(allDiffs[i],valToAppend)
# allDiffs

[array([ 0,  3,  6,  9, 12, 15, 18]),
 array([3, 3, 3, 3, 3, 3]),
 array([0, 0, 0, 0, 0])]