In [1]:
# Import packages
import numpy as np
curDay = 9

# Download input file
from download_inputs import download_inputs


import os
filename = f'inputs\\day{curDay}.txt'
if not os.path.exists(filename):
    download_inputs(curDay)
else:
    print('Inputs already downloaded')

200


In [2]:
# Load input into workspace
filename = f'inputs\\day{curDay}.txt'
# curIn = np.loadtxt(filename)

inputFile = open(filename)
inputs = []
inputs = [s for s in inputFile.read().splitlines()]

print('Done loading input')

Done loading input


In [3]:
# Load test-input into workspace
filenameTest = f'inputs\\day{curDay}_test.txt'

inputFileTest = open(filenameTest)
inputsTest = []
inputsTest = [s for s in inputFileTest.read().splitlines()]

print('Done loading test-input') 

Done loading test-input


# Part 1

In [77]:
curIn = inputs
# curIn = inputsTest

In [78]:
curIn

seqs = []

for li in curIn:
    seqs.append([int(x) for x in li.split()])
seqs = np.array(seqs)


In [105]:
seqs

sol1 = 0

# seqi = 2
for seqi in range(len(seqs)):

    curS = seqs[seqi]

    # print('New seq')

    allDiffs = []
    allDiffs.append(curS)

    curDiff = allDiffs[-1]
    nonZero = True 
    while nonZero:
    # while curDiff[1] != 0:
        nextDiff = np.diff(curDiff)
        allDiffs.append(nextDiff)
        curDiff = nextDiff
        # print(np.all(np.unique(curDiff) == 0))
        if np.all(np.unique(curDiff) == 0):
            nonZero = False

    # print(curDiff)
    # print('Done')

    for i in range(-1,-len(allDiffs)-1,-1):
        if i == -1:
            valToAppend = 0
        else:
            valToAppend = allDiffs[i][-1] + allDiffs[i+1][-1]

        allDiffs[i] = np.append(allDiffs[i],valToAppend)

    sol1 += allDiffs[0][-1]

print(sol1)

1798691765


# Part 2

In [102]:
curIn = inputs
# curIn = inputsTest
curIn

seqs = []

for li in curIn:
    seqs.append([int(x) for x in li.split()])
seqs = np.array(seqs)

In [104]:
seqs

sol2 = 0

for seqi in range(len(seqs)):

    curS = seqs[seqi]

    # print('New seq')

    allDiffs = []
    allDiffs.append(curS)

    curDiff = allDiffs[-1]
    nonZero = True 
    while nonZero:
    # while curDiff[1] != 0:
        nextDiff = np.diff(curDiff)
        allDiffs.append(nextDiff)
        curDiff = nextDiff
        # print(np.all(np.unique(curDiff) == 0))
        if np.all(np.unique(curDiff) == 0):
            nonZero = False

    # print(allDiffs)
    # print('Done')

    for i in range(-1,-len(allDiffs)-1,-1):
        if i == -1:
            valToAppend = 0
        else:
            valToAppend = allDiffs[i][0] - allDiffs[i+1][0]

        # allDiffs[i] = np.append(allDiffs[i],valToAppend)
        allDiffs[i] = np.insert(allDiffs[i],0,valToAppend)
        # print(allDiffs)

    sol2 += allDiffs[0][0]


print(sol2)

1104


# Old below

In [65]:
seqs
i = 0

curS = seqs[i]

allDiffs = []
allDiffs.append(curS)

curDiff = allDiffs[-1]
while curDiff[1] != 0:
    nextDiff = np.diff(curDiff)
    allDiffs.append(nextDiff)
    curDiff = nextDiff

    

# np.diff(curS)
# curDiff
allDiffs 



[array([ 0,  3,  6,  9, 12, 15]), array([3, 3, 3, 3, 3]), array([0, 0, 0, 0])]

In [66]:
# valToAppend = 0

for i in range(-1,-len(allDiffs)-1,-1):
    if i == -1:
        valToAppend = 0
    else:
        valToAppend = allDiffs[i][-1] + allDiffs[i+1][-1]

    allDiffs[i] = np.append(allDiffs[i],valToAppend)
allDiffs

[array([ 0,  3,  6,  9, 12, 15, 18]),
 array([3, 3, 3, 3, 3, 3]),
 array([0, 0, 0, 0, 0])]

In [54]:
i = -1
valToAppend = allDiffs[i][-1]
valToAppend


allDiffs[i] = np.append(allDiffs[i],valToAppend)


allDiffs

[array([ 0,  3,  6,  9, 12, 15]),
 array([3, 3, 3, 3, 3]),
 array([0, 0, 0, 0, 0])]

In [55]:
for i in range(-2,-len(allDiffs)-1,-1):
    valToAppend = allDiffs[i][-1] + allDiffs[i+1][-1]


    allDiffs[i] = np.append(allDiffs[i],valToAppend)
allDiffs

[array([ 0,  3,  6,  9, 12, 15, 18]),
 array([3, 3, 3, 3, 3, 3]),
 array([0, 0, 0, 0, 0])]

In [56]:
allDiffs[0][-1]

18

In [42]:
# i = -3
# valToAppend = allDiffs[i][-1] + allDiffs[i+1][-1]


# allDiffs[i] = np.append(allDiffs[i],valToAppend)
# allDiffs

[array([ 0,  3,  6,  9, 12, 15, 18]),
 array([3, 3, 3, 3, 3, 3]),
 array([0, 0, 0, 0, 0])]