In [1]:
# Import packages
import numpy as np
curDay = 16

# Download input file
from download_inputs import download_inputs


from tqdm import tqdm


import os
filename = f'inputs\\day{curDay}.txt'
if not os.path.exists(filename):
    download_inputs(curDay)
else:
    print('Inputs already downloaded')

Inputs already downloaded


In [2]:
# Load input into workspace
filename = f'inputs\\day{curDay}.txt'

inputFile = open(filename)
inputs = [s for s in inputFile.read().splitlines()]

print('Done loading input')

Done loading input


In [3]:
# Load test-input into workspace
filenameTest = f'inputs\\day{curDay}_test.txt'

inputFileTest = open(filenameTest)
inputsTest = [s for s in inputFileTest.read().splitlines()]

print('Done loading test-input') 

Done loading test-input


# Parse input

In [4]:
isTesting = True 


In [5]:
if isTesting:
    curMap = inputsTest.copy()
else:
    curMap = inputs.copy()
curMap = np.array(curMap)

In [6]:
he = len(curMap)
wi = len(curMap[0])
newMap = np.empty((he,wi),dtype='str')
for y,li in enumerate(curMap):
    for x,s in enumerate(li):
        newMap[y,x] = s




In [7]:
newMap[newMap == '\\'] = 'Y'

In [8]:
curMap = newMap

# Part 1 
Idea: Represent light on a tile with a binary value

0000: No light

0001: Right

0010: Left

0100: Up

1000: Down

So:
value = 8 * down + 4 * up + 2* left + 1 * right

In [71]:
lightVals = np.zeros(curMap.shape)

# lightVals

In [84]:
liR = np.zeros(curMap.shape)
liL = np.zeros(curMap.shape)
liU = np.zeros(curMap.shape)
liD = np.zeros(curMap.shape)

In [89]:
liR[0,0] = 1
liR[0,7] = 1
# liR[0,4] = 4

In [101]:

ys,xs = np.where(liR)

for i in range(len(ys)):
    y = ys[i]
    x = xs[i]

    print('Checking',x,y)
    
    if (x < 0) & (x >= wi-1):
        if curMap[y,x+1] == '.':
            liR[y,x+1] = 1
            print(x+1,y)

        

Checking 0 0
Checking 7 0
Checking 8 0
Checking 9 0


In [103]:
liR

array([[1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
lightVals[0,0] = 1 

# lightVals[8,4] = 1 


In [68]:

lightRight = (lightVals % 2) == True
ys,xs = np.where(lightRight)


for i in range(len(ys)):
    y = ys[i]
    x = xs[i]

    print(x,y)
    
    if (x > 0) & (x <= wi):

        

0 0


In [ ]:

pos = np.array([0,0])
dir = np.array([1,0])

numSteps = 30
tempMap = curMap.copy()

for i in range(numSteps):

    newPos = pos+dir
    

    if (newPos[0] < 0) | (newPos[1] < 0) | (newPos[0] >= wi) | (newPos[1] >= he):
        print('Outside')
        break
        

    newEnc = curMap[newPos[1],newPos[0]]

    if newEnc == '.':
        # pos = newPos 
        2+2
    elif newEnc == '|':
        if dir[0] == 0:
            # Do nothing
            # pos = newPos 
            2+2
        else:
            ### Split in two 
            ## TODO 
            # pos = newPos 
            dir = np.array([0,1])
            
    elif newEnc == '-':
        if dir[1] == 0:
            # Do nothing
            pos = newPos 
        else:
            ### Split in two 
            ## TODO 
            dir = np.array([1,0])

    elif newEnc == '/':
        # print(pos,dir)
        if dir[1] == 0:
            if dir[0] == 1: # Going right
                dir = np.array([0,-1]) # going up
            elif dir[0] == -1: # Going left
                dir = np.array([0,1]) # going down
        else:
            if dir[1] == 1: # Going down
                dir = np.array([-1,0]) # going left
            elif dir[1] == -1: # Going up
                dir = np.array([1,0]) # going right
                
        # print(pos,dir)

    elif newEnc == 'Y':
        if dir[1] == 0:
            if dir[0] == 1: # Going right
                dir = np.array([0,1]) # going down
            elif dir[0] == -1: # Going left
                dir = np.array([0,-1]) # going up
        else:
            if dir[1] == 1: # Going down
                dir = np.array([1,0]) # going right
            elif dir[1] == -1: # Going up
                dir = np.array([-1,0]) # going left
        
    pos = newPos 

    tempMap[pos[1],pos[0]] = '*'


    print(pos,dir)
    # print(tempMap)


# Old part 1 stuff

In [20]:
# # curX = 0
# # curY = 0
# pos = np.array([0,0])
# # dir = np.array([1,0])

# dd = {
#     'U':np.array([0,-1]),
#     'D':np.array([0,1]),
#     'R':np.array([1,0]),
#     'L':np.array([-1,0]),
# }
# dir = dd['R']


array([1, 0])

In [46]:

pos = np.array([0,0])
dir = np.array([1,0])

numSteps = 30
tempMap = curMap.copy()

for i in range(numSteps):

    newPos = pos+dir
    

    if (newPos[0] < 0) | (newPos[1] < 0) | (newPos[0] >= wi) | (newPos[1] >= he):
        print('Outside')
        break
        

    newEnc = curMap[newPos[1],newPos[0]]

    if newEnc == '.':
        # pos = newPos 
        2+2
    elif newEnc == '|':
        if dir[0] == 0:
            # Do nothing
            # pos = newPos 
            2+2
        else:
            ### Split in two 
            ## TODO 
            # pos = newPos 
            dir = np.array([0,1])
            
    elif newEnc == '-':
        if dir[1] == 0:
            # Do nothing
            pos = newPos 
        else:
            ### Split in two 
            ## TODO 
            dir = np.array([1,0])

    elif newEnc == '/':
        # print(pos,dir)
        if dir[1] == 0:
            if dir[0] == 1: # Going right
                dir = np.array([0,-1]) # going up
            elif dir[0] == -1: # Going left
                dir = np.array([0,1]) # going down
        else:
            if dir[1] == 1: # Going down
                dir = np.array([-1,0]) # going left
            elif dir[1] == -1: # Going up
                dir = np.array([1,0]) # going right
                
        # print(pos,dir)

    elif newEnc == 'Y':
        if dir[1] == 0:
            if dir[0] == 1: # Going right
                dir = np.array([0,1]) # going down
            elif dir[0] == -1: # Going left
                dir = np.array([0,-1]) # going up
        else:
            if dir[1] == 1: # Going down
                dir = np.array([1,0]) # going right
            elif dir[1] == -1: # Going up
                dir = np.array([-1,0]) # going left
        
    pos = newPos 

    tempMap[pos[1],pos[0]] = '*'


    print(pos,dir)
    # print(tempMap)


[1 0] [0 1]
[1 1] [0 1]
[1 2] [0 1]
[1 3] [0 1]
[1 4] [0 1]
[1 5] [0 1]
[1 6] [0 1]
[1 7] [1 0]
[2 7] [1 0]
[3 7] [1 0]
[4 7] [ 0 -1]
[4 6] [1 0]
[5 6] [1 0]
[6 6] [0 1]
[6 7] [0 1]
[6 8] [1 0]
[7 8] [0 1]
[7 9] [0 1]
Outside


array([ 7, 10])

In [81]:
curMap

array([['.', '|', '.', '.', '.', 'Y', '.', '.', '.', '.'],
       ['|', '.', '-', '.', 'Y', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '|', '-', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '|', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', 'Y'],
       ['.', '.', '.', '.', '/', '.', 'Y', 'Y', '.', '.'],
       ['.', '-', '.', '-', '/', '.', '.', '|', '.', '.'],
       ['.', '|', '.', '.', '.', '.', '-', '|', '.', 'Y'],
       ['.', '.', '/', '/', '.', '|', '.', '.', '.', '.']], dtype='<U1')

In [28]:
# np.array(curMap)[0,2]
# np.hstack(np.array([[x for x in curMap]]))
curMap = np.array([np.array(x) for x in curMap])


In [55]:
# x = np.array(curMap[2])
# x.reshape((x.size,-1))

# curMap.reshape((curMap.size,-1)) 



array([['.|...\\....'],
       ['|.-.\\.....'],
       ['.....|-...'],
       ['........|.'],
       ['..........'],
       ['.........\\'],
       ['..../.\\\\..'],
       ['.-.-/..|..'],
       ['.|....-|.\\'],
       ['..//.|....']], dtype='<U10')